### ISSUE TITLE
Allow "repository.credentials" in argo cd configuration of boom

### ISSUE THREAD

**Issue by buehler** [caos/boom#96]
There is a neat feature of argo, which allows to template credentials for whole git groups / organisations. So instead of referencing and listing _all_ ops repositores, one could (for whole projects that contain multiple repositories, or small orgas) use a credential template:

https://argoproj.github.io/argo-cd/user-guide/private-repositories/#credential-templates

and instead of 
```yaml
repositories:
- ...
- ...
```

you could use:

```yaml
repository.credentials: |
  - name: my group
    url: git@gitlab.com:GROUPNAME
    sshPrivateKeySecret:
      name: secretname
      key: keyname
```
